### ISSUE TITLE
bug on product edit - product image

### ISSUE THREAD

**Issue by jpbelo** [artprojectgroup/woocommerce-apg-weight-and-postcodestatecountry-shipping#1]
when the plugin is active, I can't add the featured image for the product cover. I deactivated and activated it several times and when it's deactivated everything works fine.
I'm on wordpress 4.9.2 and woocommerce 3.2.6

**Comment by artprojectgroup** [comment]
This plugin just work on cart and checkout, never on product edit.

Can you send us the error log lines with our plugin path?

Kind regards.

**Comment by jpbelo** [comment]
I might have not explained my issue in the best form, so I made a small vid so you can see what is happening. ( http://dev.joaobelo.pt/bug.mov )

I would be glad to but I'm not sure how to do that.

**Comment by artprojectgroup** [comment]
We understood what did you said in the first comment, but you don't read what we said :-D

Probably that issue isn't generated by our plugin because our plugin never work on that area. We just need your error log.

Kind regards.

**Comment by jpbelo** [comment]
My apologies, I misunderstood.

I'm not a advanced wordpress developer, can you provide me the steps to retrieve this error log?

**Comment by artprojectgroup** [comment]
Try to search on your cPanel or Plesk. You can search on your FTP too.

Kind regards.

**Comment by artprojectgroup** [comment]
Check this: https://codex.wordpress.org/Debugging_in_WordPress

**Comment by artprojectgroup** [comment]
In our tests there isn't any issue with featured images on products or posts.

Kind regards.
