### ISSUE TITLE
apg_shipping_pago is called on every admin page

### ISSUE THREAD

**Issue by ponys** [artprojectgroup/woocommerce-apg-weight-and-postcodestatecountry-shipping#2]
The apg_shipping_pago function is hook to "admin_init" causing it to be called on every call to an admin page, and since the function make a call to get all the payment_gatways and in cause of using an external gateway it may cause an additional external API request on each call causing a performance issue on all the admin pages.

As it can be seen on the following new relic trace for wp-admin/post.php page : 
![image](https://user-images.githubusercontent.com/3799571/91371407-48057400-e7e7-11ea-89c3-d9161c59dd63.png)

Since "$medios_de_pago" is only used on the settings page by "apg_shipping_dame_metodos_de_pago" I guess that block can be added in that function and only perform that call in that place.

**Comment by artprojectgroup** [comment]
Thank you for your report.

As soon as possible we'll fix it.

Kind regards.

**Comment by artprojectgroup** [comment]
Fixed in the next update.

Kind regards.
